[id="gridstack-options-grid"]
= Grid options

[id="api-grid-option-acceptwidgets"]
acceptWidgets::
Accept widgets dragged from other grids or from outside.
One of the following values:

* `true` will accept an HTML element having `grid-stack-item` as a class name, does not accept other element classes
* _string_ containing an explicit class name of grid items to accept
* _function (el: Element)_: boolean function called before an item will be accepted when entering a grid.
The function will be passed the item being dragged and must return `{true|false}`.

+
See also https://github.com/gridstack/gridstack.js/blob/master/demo/two.html[two-grid demo source].

+
Default: `false`

alwaysShowResizeHandle::
Controls display of resizing handles on widgets.
+
NOTE: Does not apply to non-resizable widgets.
+
One of the following values:

* `false` -- the resizing handles are only shown while hovering over a widget
* `true` -- the resizing handles are always shown
* `'mobile'` -- if running on a mobile device, default to `true` (since there is no hovering per say), else `false`.
See also http://gridstack.github.io/gridstack.js/demo/mobile.html[mobile demo].

+
Default: `'mobile'`

animate:: _(boolean)_
Enables animation to smoothen transitions.
+
Default: `true`

auto:: _(boolean)_
GridStack will initialize existing items automatically.
+
Default: `true`

cellHeight:: 
Height of a single grid cell.
One of the following values:

* _integer_ (px)
* _string_, such as `'100px'`, `'10em'`, `'10rem'`, `'10cm'`.
+
NOTE: `%` doesn't work correctly.
See http://gridstackjs.com/demo/cell-height.html[CellHeight demo].
* `0` -- the library will not generate CSS styles for rows; everything must be defined in your own CSS files.
* `'auto'` -- height will be calculated for square cells (width/column) and updated live as you resize the window; see also xref:cellHeightThrottle[cellHeightThrottle].
* `'initial'` -- similar to `auto` (start at square cells) but keep that size during window resizing.

+
Default: `'auto'`

[id="cellHeightThrottle"]
cellHeightThrottle?:: _(number)_
Throttle time delay (in ms) used when `cellHeight='auto'` to improve performance vs usability.
+
WARNING: The `0` value will make it instant at the cost of re-creating the CSS file at ever window resize event!
+
Default?: `100`

children?:: _(xref:gridstackwidget-options.adoc[GridStackWidget[\]])_
A list of grid items to create when calling `load()` or `addGrid()`.

column::
The number of columns in a grid:

* _integer > 0_ -- this can change on the fly with column(N) method;
see also http://gridstackjs.com/demo/column.html[column demo].
* `'auto'` -- for nested grids to size themselves to the parent grid container to make sub-items the same size;
see also http://gridstackjs.com/demo/nested.html[nested demo].

+
Default: `12`

columnOpts?:: _(xref:gridstack-options-responsive[Responsive])_
Describes the responsive nature of the column grid.
+
Default: `???`

class?:: _(string)_
An additional CSS class on top of `.grid-stack`, which is required for our CSS to differentiate this grid instance from other grids in a multi-grid setup.

disableDrag:: _(boolean)_
Disables dragging of widgets.
+
Default: `false`

disableResize:: _(boolean)_
Disables resizing of widgets.
+
Default: `false`

draggable:: _(xref:gridstack-options-dddragopt[DDDragOpt])_
Override draggable options.
+
Default: `{handle: '.grid-stack-item-content', appendTo: 'body', scroll: true}`

engineClass:: _(JavaScript class)_
The JavaScript class of the engine to create.
If you have a subclass of the `GridStackEngine`, you can register it here.
+
Default: `GridStackEngine`

float:: _(boolean)_
Enable floating widgets.
See example.
+
Default: `false`

handle:: _(string)_
Draggable handle class selector. 
+
Default: `'.grid-stack-item-content'`

handleClass:: _(string)_
Draggable handle class, such as `'grid-stack-item-content'`.
If set, `handle` is ignored.
+
Default: `null`

itemClass:: _(string)_
Grid item (widget) class.
+
Default: `'grid-stack-item'`

lazyLoad?:: _(boolean)_ 
Create widgets only when they scroll into view (visible).
Also overridable per widget in xref:gridstackwidget-options.adoc[GridStackWidget].
+
Default: `???`

margin::
The gap size around grid item and content.
One of the following values:

* _integer_ (px)
* _string_, such as `'2em'`, `'20px'`, `'2rem'`

+
You can also set the margins individually (default to `margin`): *marginTop*, *marginRight*, *marginBottom*, *marginLeft*.

maxRow:: _(integer)_
The maximum number of rows.
+
Default: `0` (unlimited)

minRow:: _(integer)_
The minimum number of rows, which is handy to prevent grid from collapsing when empty. 
When not set, the `min-height` CSS attribute on the grid `<div>` (in pixels) can be used, which will round to the closest row.
+
Default: `0`

nonce::
If you are using a nonce-based Content Security Policy, pass your nonce here and GridStack will add it to the `<style>` elements it creates.

placeholderClass:: _(string)_
Widget placeholder class.
+
Default: `'grid-stack-placeholder'`

placeholderText:: _(string)_
Widget placeholder default content.
+
Default: `''` (empty)

resizable:: _({handles: 'string'})_
Define locations of handles by which widgets can be resized.
Handles _string_ can be any combo of `'n,ne,e,se,s,sw,w,nw'` or `'all'`.
+
Default: `{handles: 'se'}` (south east)

removable:: _(boolean or string)_
Enable removal of widgets by dragging them outside of the grid.
+
The value can also be a selector string. In this case, widgets will be removed by dropping them there.
See also http://gridstackjs.com/demo/two.html[two-grid demo].
+
Default: `false`

removeTimeout:: _(integer)_
Time in milliseconds before widget is removed when dragged outside of the grid.
+
Default: `2000`

row::
Fixed number of grid rows.
This is a shortcut of `minRow: N` and `maxRow: N`.
+
Default: `0` (no constraint)

rtl::
Turns grid Right-to-Left.
See also https://gridstackjs.com/demo/right-to-left(rtl).html[right-to-left demo].
+
Possible values: `true`, `false`, `'auto'`
+
Default: 'auto'

sizeToContent:: _(boolean)_
Size grid items automatically according to their content, calling resizeToContent(el) whenever the grid or item is resized.
+
Default: `???`

staticGrid::
Disables drag&drop and resize.
If disabled, the user cannot move or resize widgets, but code can still move and oneColumnMode will still work.
The CSS class `grid-stack-static` is also added to the grid stack container.
+
TIP: You can use the smaller `gridstack-static.js` library.
+
Default: `false`
