= Events

Those are events generated by the grid when items are added/removed/changed or drag&drop interaction.
In general, they pass a list of nodes that has changed (id, x, y, width, height, and so on) or an individual DOM element that is affected.

You can listen on a single event or a space-separated list of events, such as `grid.on('added removed change', ...)`.

The Typescript `GridStackEvent` lists all possible values and nothing else is supported by the `grid.on()` method, though it's possible to register directly for other events generated by the drag&drop plugging implementation detail (if jquery-ui based you can still use `$(".grid-stack").on(...)`).

== Overview

*Events*: xref:event-added[added] | xref:event-change[change] | xref:event-disable[disable] | xref:event-dragstart[dragstart] | xref:event-drag[drag] | xref:event-dragstop[dragstop] | xref:event-dropped[dropped] | xref:event-enable[enable] | xref:event-removed[removed] | xref:event-resizestart[resizestart] | xref:event-resize[resize] | xref:event-resizestop[resizestop] | xref:event-preparedragdrop[prepareDragDrop]

== Event details

[id="event-added"]
added(event, items)::
Called when widgets are being added to a grid.
+
[source,javascript]
----
grid.on('added', function(event: Event, items: GridStackNode[]) {
  items.forEach(function(item) {...});
});
----

[id="event-change"]
change(event, items)::
Occurs when widgets change their position/size due to constrain or direct changes
+
[source,javascript]
----
grid.on('change', function(event: Event, items: GridStackNode[]) {
  items.forEach(function(item) {...});
});
----

[id="event-disable"]
disable(event)::
+
[source,javascript]
----
grid.on('disable', function(event: Event) {
  let grid: GridStack = event.target.gridstack;
});
----

[id="event-dragstart"]
dragstart(event, el)::
called when grid item is starting to be dragged
+
[source,javascript]
----
grid.on('dragstart', function(event: Event, el: GridItemHTMLElement) {
});
----

[id="event-drag"]
drag(event, el)::
called while grid item is being dragged, for each new row/column value (not every pixel)
+
[source,javascript]
----
grid.on('drag', function(event: Event, el: GridItemHTMLElement) {
});
----

[id="event-dragstop"]
dragstop(event, el)::
called after the user is done moving the item, with updated DOM attributes.
+
[source,javascript]
----
grid.on('dragstop', function(event: Event, el: GridItemHTMLElement) {
  let x = parseInt(el.getAttribute('gs-x')) || 0;
  // or all values...
  let node: GridStackNode = el.gridstackNode; // {x, y, width, height, id, ....}
});
----

[id="event-dropped"]
dropped(event, previousWidget, newWidget)::
called when an item has been dropped and accepted over a grid. If the item came from another grid, the previous widget node info will also be sent (but dom item long gone).
+
[source,javascript]
----
grid.on('dropped', function(event: Event, previousWidget: GridStackNode, newWidget: GridStackNode) {
  console.log('Removed widget that was dragged out of grid:', previousWidget);
  console.log('Added widget in dropped grid:', newWidget);
});
----

[id="event-enable"]
enable(event)::
+
[source,javascript]
----
grid.on('enable', function(event: Event) {
  let grid: GridStack = event.target.gridstack;
});
----

[id="event-removed"]
removed(event, items)::
Called when items are being removed from the grid
+
[source,javascript]
----
grid.on('removed', function(event: Event, items: GridStackNode[]) {
  items.forEach(function(item) {...});
});
----

[id="event-resizestart"]
resizestart(event, el)::
called before the user starts resizing an item
+
[source,javascript]
----
grid.on('resizestart', function(event: Event, el: GridItemHTMLElement) {
});
----

[id="event-resize"]
resize(event, el)::
called while grid item is being resized, for each new row/column value (not every pixel)
+
[source,javascript]
----
grid.on('resize', function(event: Event, el: GridItemHTMLElement) {
});
----

[id="event-resizestop"]
resizestop(event, el)::
called after the user is done resizing the item, with updated DOM attributes.
+
[source,javascript]
----
grid.on('resizestop', function(event: Event, el: GridItemHTMLElement) {
  let width = parseInt(el.getAttribute('gs-w')) || 0;
  // or all values...
  let node: GridStackNode = el.gridstackNode;
  // {x, y, width, height, id, ...}
});
----

[id="event-preparedragdrop"]
prepareDragDrop(el: GridItemHTMLElement, force = false) : GridStack::
prepares the element for drag&drop - this is normally called by makeWiget() unless are are delay loading

* `el` -- GridItemHTMLElement of the widget
* `force=false`
